name: iwrqk
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  animations: ^2.1.1
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  audio_video_progress_bar: ^2.0.3
  auto_orientation_v2: ^2.3.7
  auto_size_text: ^3.0.0
  background_downloader: ^9.4.0
  cached_network_image: ^3.4.1
  cloudflare_interceptor: ^0.0.3
  cookie_jar: ^4.0.8
  crypto: ^3.0.7
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  dynamic_color: ^1.8.1
  easy_debounce: ^2.0.3
  easy_refresh: ^3.4.0
  file_picker: ^10.3.7
  floating: ^6.0.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.7.0
  flutter_secure_storage: ^9.2.4
  flutter_smart_dialog: ^4.9.8+9
  flutter_volume_controller: ^1.3.4
  get: ^4.7.3
  get_storage: ^2.1.1
  html: ^0.15.6
  http: ^1.6.0
  intl: ^0.20.2
  listen_sharing_intent: ^1.9.2
  logger: ^2.6.2
  markdown_widget: ^2.3.2+8
  media_kit: ^1.2.2
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.0
  open_file: ^3.5.10
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  queue: ^3.4.0
  screen_brightness: ^2.1.7
  share_plus: ^12.0.1
  slang: ^4.11.0
  slang_flutter: ^4.11.0
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
  adaptive_icon_monochrome: "assets/launcher/foreground.png"
  windows:
    generate: true
    image_path: "assets/launcher/icon.png"
  macos:
    generate: true
    image_path: "assets/launcher/icon.png"
